-- 1. CLEANUP SECTION
SELECT name, open_mode FROM v$pdbs; 

-- Close the PDB first
ALTER PLUGGABLE DATABASE STIS_PDB CLOSE IMMEDIATE;

-- Drop it and remove its datafiles
DROP PLUGGABLE DATABASE STIS_PDB INCLUDING DATAFILES;

-- Cleanup complete; Re-enable error stopping for critical commands
WHENEVER SQLERROR EXIT FAILURE 

-- Check Archive Log status (CRITICAL FOR AUDITING IN PHASE VII)
SELECT log_mode FROM v$database;

-- 2. CREATE THE PLUGGABLE DATABASE (PDB)
CREATE PLUGGABLE DATABASE STIS_PDB
  ADMIN USER pdb_admin IDENTIFIED BY 1111
  ROLES = (DBA)
  FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/ORCLCDB/pdbseed/',
    '/opt/oracle/oradata/ORCLCDB/STIS_PDB/' 
);

-- 3. OPEN THE NEW PDB
ALTER PLUGGABLE DATABASE STIS_PDB OPEN;

-- Add Persistence 
ALTER PLUGGABLE DATABASE STIS_PDB SAVE STATE;

-- 4. SWITCH TO THE NEW PDB TO CREATE TABLESPACES
-- ALTER SESSION SET CONTAINER = STIS_PDB;

-- 5. CREATE DEDICATED TABLESPACES (REQUIRED)
WHENEVER SQLERROR CONTINUE
-- Drop existing tablespaces, including their datafiles
DROP TABLESPACE STIS_DATA_TS INCLUDING CONTENTS AND DATAFILES; 
DROP TABLESPACE STIS_INDEX_TS INCLUDING CONTENTS AND DATAFILES;
WHENEVER SQLERROR EXIT FAILURE

-- 5a. Data Tablespace
CREATE TABLESPACE STIS_DATA_TS
  DATAFILE '/opt/oracle/oradata/ORCLCDB/STIS_PDB/stis_data_04.dbf' SIZE 100M
  AUTOEXTEND ON NEXT 50M MAXSIZE 5G
  LOGGING
  ONLINE;

-- 5b. Index Tablespace
CREATE TABLESPACE STIS_INDEX_TS
  DATAFILE '/opt/oracle/oradata/ORCLCDB/STIS_PDB/stis_index_04.dbf' SIZE 50M
  AUTOEXTEND ON NEXT 25M MAXSIZE 2G
  LOGGING
  ONLINE;

-- 6. VERIFY TABLESPACE CREATION
SELECT tablespace_name, file_name, autoextensible FROM dba_data_files;

-- 7. RETURN TO CDB
-- ALTER SESSION SET CONTAINER = CDB$ROOT;