-- 1. CONNECT TO THE NEW PDB (e.g., sqlplus sys/password@//localhost:1521/STIS_PDB as sysdba)
-- Admin User Naming Format: GrpName_StudentId_FirstName_ProjectName_DB (Based on requirements)

-- Define user details
DEFINE ADMIN_USERNAME = 'STIS_ADMIN_28179'
DEFINE ADMIN_PASSWORD = 'varma' -- User's first name
DEFINE DEFAULT_TS = 'STIS_DATA_TS'
DEFINE TEMP_TS = 'TEMP' 

-- 2. CREATE THE PROJECT USER
CREATE USER &ADMIN_USERNAME IDENTIFIED BY &ADMIN_PASSWORD
  DEFAULT TABLESPACE &DEFAULT_TS
  TEMPORARY TABLESPACE &TEMP_TS
  QUOTA UNLIMITED ON STIS_DATA_TS
  QUOTA UNLIMITED ON STIS_INDEX_TS
  ACCOUNT UNLOCK;

-- 3. GRANT SUPER ADMIN PRIVILEGES (REQUIRED)
GRANT CONNECT TO &ADMIN_USERNAME;
GRANT RESOURCE TO &ADMIN_USERNAME; 
GRANT CREATE SESSION TO &ADMIN_USERNAME;
GRANT CREATE TABLE TO &ADMIN_USERNAME;
GRANT CREATE PROCEDURE TO &ADMIN_USERNAME;
GRANT CREATE TRIGGER TO &ADMIN_USERNAME;
GRANT CREATE SEQUENCE TO &ADMIN_USERNAME;
GRANT UNLIMITED TABLESPACE TO &ADMIN_USERNAME; 

-- 4. VERIFY USER CREATION
SELECT username, default_tablespace FROM dba_users WHERE username = UPPER('&ADMIN_USERNAME');