-- 1. CONNECT TO THE NEW PDB 
SELECT name, open_mode FROM v$pdbs;
ALTER SESSION SET CONTAINER = STIS_PDB;
SELECT tablespace_name, file_name, autoextensible FROM dba_data_files;

-- CLEANUP SECTION
WHENEVER SQLERROR CONTINUE
-- Drop user cascade will drop the user and all their objects (for reliable re-testing)
DROP USER STIS_ADMIN_28179 CASCADE;
WHENEVER SQLERROR EXIT FAILURE

-- 2. CREATE THE PROJECT USER
-- This is the Application Schema Owner who will create all Tables, Procedures, and Triggers.
CREATE USER STIS_ADMIN_28179 IDENTIFIED BY varma 
  DEFAULT TABLESPACE STIS_DATA_TS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON STIS_DATA_TS
  QUOTA UNLIMITED ON STIS_INDEX_TS
  ACCOUNT UNLOCK;

-- 3. GRANT SUPER ADMIN PRIVILEGES (REQUIRED)
GRANT CONNECT TO STIS_ADMIN_28179;
GRANT RESOURCE TO STIS_ADMIN_28179; 
GRANT CREATE SESSION TO STIS_ADMIN_28179;
GRANT CREATE TABLE TO STIS_ADMIN_28179;
GRANT CREATE PROCEDURE TO STIS_ADMIN_28179; -- Grants permission to create Phase VI Procedures/Functions
GRANT CREATE TRIGGER TO STIS_ADMIN_28179; -- Grants permission to create Phase VII Triggers
GRANT CREATE SEQUENCE TO STIS_ADMIN_28179;
GRANT UNLIMITED TABLESPACE TO STIS_ADMIN_28179; 

-- 4. VERIFY USER CREATION
SELECT username, default_tablespace FROM dba_users WHERE username = 'STIS_ADMIN_28179';
