-- Connect as the project user: STIS_ADMIN_28179
-- 1. CLEANUP SECTION
WHENEVER SQLERROR CONTINUE

DROP TABLE PLANTING_BATCHES CASCADE CONSTRAINTS;
DROP TABLE FARM_SUPPLIES CASCADE CONSTRAINTS;
DROP TABLE CROP_TYPES CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE seq_batch_id;
DROP SEQUENCE seq_supply_id;
DROP SEQUENCE seq_crop_id;

WHENEVER SQLERROR EXIT FAILURE

-- 2. CREATE SEQUENCES (Starting point corrected for FARM_SUPPLIES)
CREATE SEQUENCE seq_crop_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_supply_id START WITH 104 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_batch_id START WITH 1000 INCREMENT BY 1 NOCACHE;


-- 3. CREATE CORE TABLES (Remains unchanged)
-- ... (Table creation DDL is the same as before)
-- 3a. CROP_TYPES
CREATE TABLE CROP_TYPES (
    CROP_ID             NUMBER(10)          PRIMARY KEY,
    CROP_NAME           VARCHAR2(100)       NOT NULL UNIQUE,
    GROWTH_DAYS         NUMBER(3)           NOT NULL,
    YIELD_PER_UNIT      NUMBER(10, 2)
) TABLESPACE STIS_DATA_TS;

-- 3b. FARM_SUPPLIES
CREATE TABLE FARM_SUPPLIES (
    SUPPLY_ID           NUMBER(10)          PRIMARY KEY,
    ITEM_NAME           VARCHAR2(100)       NOT NULL,
    CURRENT_STOCK       NUMBER(10, 2)       NOT NULL,
    UNIT_OF_MEASURE     VARCHAR2(20)        NOT NULL,
    
    CONSTRAINT chk_positive_stock CHECK (CURRENT_STOCK >= 0)
) TABLESPACE STIS_DATA_TS;


-- *** UPDATED DDL for PLANTING_BATCHES (Must run this again) ***
CREATE TABLE PLANTING_BATCHES (
    BATCH_ID                    NUMBER(10)          PRIMARY KEY,
    CROP_ID                     NUMBER(10)          NOT NULL,
    -- ADDED: The SUPPLY_ID column linked to FARM_SUPPLIES
    SUPPLY_ID                   NUMBER(10)          NOT NULL, 
    PLANTING_DATE               DATE                NOT NULL,
    EXPECTED_HARVEST_DATE       DATE,
    AREA_PLANTED_SQM            NUMBER(10, 2)       NOT NULL,
    SEEDS_CONSUMED              NUMBER(10, 2)       NOT NULL,
    STATUS                      VARCHAR2(20)        NOT NULL,

    CONSTRAINT fk_batch_crop FOREIGN KEY (CROP_ID) REFERENCES CROP_TYPES(CROP_ID),
    -- ADDED: Foreign Key Constraint for the supply used
    CONSTRAINT fk_batch_supply FOREIGN KEY (SUPPLY_ID) REFERENCES FARM_SUPPLIES(SUPPLY_ID)
    -- ... other constraints
) TABLESPACE STIS_DATA_TS;


