-- Connect as the project user: STIS_ADMIN_28179
SET SERVEROUTPUT ON

-- 1. CLEANUP SECTION
WHENEVER SQLERROR CONTINUE

DROP TABLE PLANTING_BATCHES CASCADE CONSTRAINTS;
DROP TABLE FARM_SUPPLIES CASCADE CONSTRAINTS;
DROP TABLE CROP_TYPES CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE seq_batch_id;
DROP SEQUENCE seq_supply_id;
DROP SEQUENCE seq_crop_id;

-- Drop Trigger (Ensuring clean rebuild)
DROP TRIGGER TRG_BATCH_ID_POPULATE;

WHENEVER SQLERROR EXIT FAILURE

-- 2. CREATE SEQUENCES
CREATE SEQUENCE seq_crop_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_supply_id START WITH 104 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_batch_id START WITH 1000 INCREMENT BY 1 NOCACHE;


-- 3. CREATE CORE TABLES
-- 3a. CROP_TYPES (Reference Data)
CREATE TABLE CROP_TYPES (
    CROP_ID             NUMBER(10)          PRIMARY KEY,
    CROP_NAME           VARCHAR2(100)       NOT NULL UNIQUE,
    GROWTH_DAYS         NUMBER(3)           NOT NULL,
    YIELD_PER_UNIT      NUMBER(10, 2)
) TABLESPACE STIS_DATA_TS;

-- 3b. FARM_SUPPLIES (Inventory Data)
CREATE TABLE FARM_SUPPLIES (
    SUPPLY_ID           NUMBER(10)          PRIMARY KEY,
    ITEM_NAME           VARCHAR2(100)       NOT NULL,
    CURRENT_STOCK       NUMBER(10, 2)       NOT NULL,
    UNIT_OF_MEASURE     VARCHAR2(20)        NOT NULL,
    
    CONSTRAINT chk_positive_stock CHECK (CURRENT_STOCK >= 0)
) TABLESPACE STIS_DATA_TS;

CREATE TABLE PLANTING_BATCHES (
    BATCH_ID                    NUMBER(10)          PRIMARY KEY,
    CROP_ID                     NUMBER(10)          NOT NULL,
    SUPPLY_ID                   NUMBER(10)          NOT NULL, 
    PLANTING_DATE               DATE                NOT NULL,
    EXPECTED_HARVEST_DATE       DATE,
    AREA_PLANTED_SQM            NUMBER(10, 2)       NOT NULL,
    SEEDS_CONSUMED              NUMBER(10, 2)       NOT NULL,
    STATUS                      VARCHAR2(20)        NOT NULL,

    CONSTRAINT fk_batch_crop FOREIGN KEY (CROP_ID) REFERENCES CROP_TYPES(CROP_ID),
    CONSTRAINT fk_batch_supply FOREIGN KEY (SUPPLY_ID) REFERENCES FARM_SUPPLIES(SUPPLY_ID), 
    CONSTRAINT chk_batch_status CHECK (STATUS IN ('PLANTED', 'GROWING', 'HARVESTED', 'FAILED')),
    CONSTRAINT chk_batch_area CHECK (AREA_PLANTED_SQM > 0),
    CONSTRAINT chk_batch_seeds CHECK (SEEDS_CONSUMED > 0)
) TABLESPACE STIS_DATA_TS;


-- 4. CREATE TRIGGER (CRITICAL FIX FOR PHASE VI)
-- This links the sequence seq_batch_id to the BATCH_ID primary key.
CREATE OR REPLACE TRIGGER TRG_BATCH_ID_POPULATE
BEFORE INSERT ON PLANTING_BATCHES
FOR EACH ROW
BEGIN
    -- If BATCH_ID is NULL (which it will be in the PL/SQL procedure), get the next sequence value.
    IF :NEW.BATCH_ID IS NULL THEN
        SELECT seq_batch_id.NEXTVAL INTO :NEW.BATCH_ID FROM DUAL;
    END IF;
END;
/


-- 5. VERIFICATION QUERIES (FOR SCREENSHOTS)
DESCRIBE  PLANTING_BATCHES;
DESCRIBE  FARM_SUPPLIES;
DESCRIBE  CROP_TYPES;


SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION 
 FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ('PLANTING_BATCHES', 'FARM_SUPPLIES');