-- Connect as the project user: STIS_ADMIN_28179
SET ECHO ON
SET VERIFY OFF
SET SERVEROUTPUT ON

-- 1. CLEANUP SECTION
WHENEVER SQLERROR CONTINUE

DROP TABLE PLANTING_BATCHES CASCADE CONSTRAINTS;
DROP TABLE FARM_SUPPLIES CASCADE CONSTRAINTS;
DROP TABLE CROP_TYPES CASCADE CONSTRAINTS;

-- Drop Sequences
DROP SEQUENCE seq_batch_id;
DROP SEQUENCE seq_supply_id;
DROP SEQUENCE seq_crop_id;

WHENEVER SQLERROR EXIT FAILURE

-- 2. CREATE SEQUENCES
CREATE SEQUENCE seq_crop_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_supply_id START WITH 104 INCREMENT BY 1 NOCACHE; 
CREATE SEQUENCE seq_batch_id START WITH 1000 INCREMENT BY 1 NOCACHE;


-- 3. CREATE CORE TABLES
-- 3a. CROP_TYPES (Reference Data)
CREATE TABLE CROP_TYPES (
    CROP_ID             NUMBER(10)          PRIMARY KEY,
    CROP_NAME           VARCHAR2(100)       NOT NULL UNIQUE,
    GROWTH_DAYS         NUMBER(3)           NOT NULL,
    YIELD_PER_UNIT      NUMBER(10, 2)
) TABLESPACE STIS_DATA_TS;

-- 3b. FARM_SUPPLIES (Inventory Data)
CREATE TABLE FARM_SUPPLIES (
    SUPPLY_ID           NUMBER(10)          PRIMARY KEY,
    ITEM_NAME           VARCHAR2(100)       NOT NULL,
    CURRENT_STOCK       NUMBER(10, 2)       NOT NULL,
    UNIT_OF_MEASURE     VARCHAR2(20)        NOT NULL,
    
    CONSTRAINT chk_positive_stock CHECK (CURRENT_STOCK >= 0)
) TABLESPACE STIS_DATA_TS;

-- 3c. PLANTING_BATCHES (Transactional Data - FIX APPLIED HERE)
CREATE TABLE PLANTING_BATCHES (
    BATCH_ID                    NUMBER(10)          PRIMARY KEY,
    CROP_ID                     NUMBER(10)          NOT NULL,
    SUPPLY_ID                   NUMBER(10)          NOT NULL, -- <<< FIX: ADDED SUPPLY_ID COLUMN
    PLANTING_DATE               DATE                NOT NULL,
    EXPECTED_HARVEST_DATE       DATE,
    AREA_PLANTED_SQM            NUMBER(10, 2)       NOT NULL,
    SEEDS_CONSUMED              NUMBER(10, 2)       NOT NULL,
    STATUS                      VARCHAR2(20)        NOT NULL,

    CONSTRAINT fk_batch_crop FOREIGN KEY (CROP_ID) REFERENCES CROP_TYPES(CROP_ID),
    CONSTRAINT fk_batch_supply FOREIGN KEY (SUPPLY_ID) REFERENCES FARM_SUPPLIES(SUPPLY_ID), -- <<< FIX: ADDED FK CONSTRAINT
    CONSTRAINT chk_batch_status CHECK (STATUS IN ('PLANTED', 'GROWING', 'HARVESTED', 'FAILED')),
    CONSTRAINT chk_batch_area CHECK (AREA_PLANTED_SQM > 0),
    CONSTRAINT chk_batch_seeds CHECK (SEEDS_CONSUMED > 0)
) TABLESPACE STIS_DATA_TS;


-- 4. INSERT REFERENCE DATA (CROP_TYPES)
INSERT INTO CROP_TYPES (CROP_ID, CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES 
(seq_crop_id.NEXTVAL, 'Maize (White)', 120, 0.5); -- CROP_ID = 1
INSERT INTO CROP_TYPES (CROP_ID, CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES 
(seq_crop_id.NEXTVAL, 'Beans (Red)', 90, 0.3); -- CROP_ID = 2
INSERT INTO CROP_TYPES (CROP_ID, CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES 
(seq_crop_id.NEXTVAL, 'Sorghum', 150, 0.6); -- CROP_ID = 3
INSERT INTO CROP_TYPES (CROP_ID, CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES 
(seq_crop_id.NEXTVAL, 'Wheat', 180, 0.4); -- CROP_ID = 4

-- 5. INSERT INITIAL INVENTORY DATA (FARM_SUPPLIES)
-- SUPPLY_ID 100 = Maize Seeds; SUPPLY_ID 102 = Beans Seeds
INSERT INTO FARM_SUPPLIES (SUPPLY_ID, ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE) VALUES 
(100, 'Maize Seeds (Hybrid)', 5000, 'KG');
INSERT INTO FARM_SUPPLIES (SUPPLY_ID, ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE) VALUES 
(101, 'Fertilizer (NPK)', 2500, 'KG');
INSERT INTO FARM_SUPPLIES (SUPPLY_ID, ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE) VALUES 
(102, 'Beans Seeds (Red Variety)', 1500, 'KG');
INSERT INTO FARM_SUPPLIES (SUPPLY_ID, ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE) VALUES 
(103, 'Sorghum Seeds', 3000, 'KG');


-- 6. INSERT BULK TRANSACTIONAL DATA
DECLARE
    v_date DATE := DATE '2024-01-01';
    v_crop_id_maize CONSTANT NUMBER := 1; 
    v_crop_id_beans CONSTANT NUMBER := 2; 
    v_supply_id_maize CONSTANT NUMBER := 100;
    v_supply_id_beans CONSTANT NUMBER := 102;
    v_count NUMBER := 0;
BEGIN
    -- Loop 1: Create 60 Maize batches
    FOR i IN 1..60 LOOP
        v_date := DATE '2024-01-01' + (i * 5);
        
        INSERT INTO PLANTING_BATCHES (BATCH_ID, CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
        VALUES (seq_batch_id.NEXTVAL, v_crop_id_maize, v_supply_id_maize, v_date, -- <<< FIX: ADDED SUPPLY_ID (100)
                DBMS_RANDOM.VALUE(100, 500), 
                DBMS_RANDOM.VALUE(5, 20),    
                CASE 
                    WHEN i < 15 THEN 'HARVESTED' 
                    ELSE 'PLANTED'
                END);
        v_count := v_count + 1;
    END LOOP;
    
    -- Loop 2: Create 45 Beans batches
    FOR i IN 1..45 LOOP
        v_date := DATE '2024-02-15' + (i * 6);
        
        INSERT INTO PLANTING_BATCHES (BATCH_ID, CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS, EXPECTED_HARVEST_DATE)
        VALUES (seq_batch_id.NEXTVAL, v_crop_id_beans, v_supply_id_beans, v_date, -- <<< FIX: ADDED SUPPLY_ID (102)
                DBMS_RANDOM.VALUE(50, 300), 
                DBMS_RANDOM.VALUE(3, 15),
                CASE 
                    WHEN i < 30 THEN 'HARVESTED' 
                    ELSE 'PLANTED'
                END,
                CASE 
                    WHEN i < 30 THEN v_date + 90 
                    ELSE NULL
                END);
        v_count := v_count + 1;
    END LOOP;

    DBMS_OUTPUT.PUT_LINE(v_count || ' transactional rows inserted into PLANTING_BATCHES.');
END;
/

COMMIT;

-- 7. VERIFICATION 
SELECT 'Total Rows in Tables' AS Table_Name, SUM(cnt) AS Total_Rows FROM (
    SELECT COUNT(*) AS cnt FROM CROP_TYPES
    UNION ALL
    SELECT COUNT(*) AS cnt FROM FARM_SUPPLIES
    UNION ALL
    SELECT COUNT(*) AS cnt FROM PLANTING_BATCHES
) q;

-- Testing (Updated JOINs to reflect new column)
SELECT 
    b.BATCH_ID,
    c.CROP_NAME,
    s.ITEM_NAME AS SEED_SUPPLY, -- New column use
    b.PLANTING_DATE,
    b.STATUS
FROM 
    PLANTING_BATCHES b
JOIN 
    CROP_TYPES c ON b.CROP_ID = c.CROP_ID
JOIN 
    FARM_SUPPLIES s ON b.SUPPLY_ID = s.SUPPLY_ID -- New JOIN
WHERE 
    b.STATUS = 'PLANTED'
FETCH FIRST 5 ROWS ONLY;

SELECT 'Verification Complete' FROM DUAL;