-- Connect as the project user: STIS_ADMIN_28179

-- 1. Insert CROP_TYPES Data
INSERT INTO CROP_TYPES (CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES ('Maize (White)', 120, 1.50);
INSERT INTO CROP_TYPES (CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES ('Tomatoes (Roma)', 75, 5.00);
INSERT INTO CROP_TYPES (CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES ('Potatoes (Irish)', 90, 2.50);
INSERT INTO CROP_TYPES (CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES ('Carrots', 60, 3.00);
INSERT INTO CROP_TYPES (CROP_NAME, GROWTH_DAYS, YIELD_PER_UNIT) VALUES ('Beans (Green)', 50, 4.20);

-- 2. Insert FARM_SUPPLIES Data (Seeds and a Non-Seed Supply)
-- Note: The PL/SQL in Phase VI will only deduct from the item used in the batch.
INSERT INTO FARM_SUPPLIES (ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE, UNIT_COST) VALUES ('Maize Seeds (Hybrid)', 500.00, 'KG', 1.50); -- SUPPLY_ID = 200
INSERT INTO FARM_SUPPLIES (ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE, UNIT_COST) VALUES ('Tomato Seeds (Roma)', 15.00, 'GRAM', 5.00); -- SUPPLY_ID = 201
INSERT INTO FARM_SUPPLIES (ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE, UNIT_COST) VALUES ('NPK Fertilizer', 1000.00, 'KG', 0.80); -- SUPPLY_ID = 202
INSERT INTO FARM_SUPPLIES (ITEM_NAME, CURRENT_STOCK, UNIT_OF_MEASURE, UNIT_COST) VALUES ('Potato Tubers', 200.00, 'COUNT', 0.25); -- SUPPLY_ID = 203

-- 3. Insert Sample PLANTING_BATCHES Data (5 Rows)
-- You must ensure the CROP_ID and SUPPLY_ID exist.
-- Use the CROP_ID and SUPPLY_ID values from the inserts above. (IDs 100, 200, 101, 201, etc.)
INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
VALUES (100, 200, DATE '2025-09-01', 50.00, 10.00, 'GROWING');

INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
VALUES (101, 201, DATE '2025-10-15', 5.00, 0.50, 'PLANTED');

INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
VALUES (102, 203, DATE '2025-08-20', 20.00, 50.00, 'HARVESTING');

INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
VALUES (103, 201, DATE '2025-11-20', 10.00, 0.20, 'PLANTED');

INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
VALUES (104, 200, DATE '2025-07-01', 100.00, 25.00, 'COMPLETED');

COMMIT;

-- Instructions for scaling data volume:
/*
To achieve the 100-500+ rows required for PLANTING_BATCHES, use a PL/SQL loop or SQL Developer's Data Generator:

BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO PLANTING_BATCHES (CROP_ID, SUPPLY_ID, PLANTING_DATE, AREA_PLANTED_SQM, SEEDS_CONSUMED, STATUS)
        VALUES (
            FLOOR(DBMS_RANDOM.VALUE(100, 104)), -- Random CROP_ID
            FLOOR(DBMS_RANDOM.VALUE(200, 203)), -- Random SUPPLY_ID (Adjust IDs based on your data)
            TRUNC(SYSDATE - DBMS_RANDOM.VALUE(10, 365)), -- Random date in the last year
            ROUND(DBMS_RANDOM.VALUE(1, 50), 2), -- Area between 1 and 50 sqm
            ROUND(DBMS_RANDOM.VALUE(0.1, 10), 2), -- Seeds consumed
            'PLANTED'
        );
    END LOOP;
    COMMIT;
END;
/
*/