-- Connect as the project user: STIS_ADMIN_28179

-- 1. Create the Audit Log Table
CREATE TABLE BATCH_AUDIT_LOG (
    LOG_ID                  NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    BATCH_ID                NUMBER(10)      NOT NULL,
    CHANGE_DATE             TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CHANGED_BY              VARCHAR2(50)    DEFAULT USER NOT NULL,
    OPERATION               VARCHAR2(10)    NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    
    -- Specific columns to track changes on
    OLD_STATUS              VARCHAR2(20),
    NEW_STATUS              VARCHAR2(20),
    OLD_HARVEST_DATE        DATE,
    NEW_HARVEST_DATE        DATE,
    OLD_AREA_SQM            NUMBER(10,2),
    NEW_AREA_SQM            NUMBER(10,2)
) TABLESPACE STIS_DATA_TS;

-- 2. Create an Index on BATCH_ID for efficient querying of a batch's history
CREATE INDEX idx_audit_batch_id ON BATCH_AUDIT_LOG (BATCH_ID) TABLESPACE STIS_INDEX_TS;