-- Connect as the project user: STIS_ADMIN_28179

-- 1. Create a simple table to log DDL activities
CREATE TABLE DDL_AUDIT_LOG (
    LOG_TIME    TIMESTAMP DEFAULT SYSTIMESTAMP,
    USER_NAME   VARCHAR2(30),
    EVENT_TYPE  VARCHAR2(30),
    OBJECT_TYPE VARCHAR2(30),
    OBJECT_NAME VARCHAR2(30)
) TABLESPACE STIS_DATA_TS;

-- 2. Create the DDL Trigger
CREATE OR REPLACE TRIGGER STIS_DDL_TRG
AFTER CREATE OR DROP OR ALTER ON SCHEMA
BEGIN
    INSERT INTO DDL_AUDIT_LOG (
        USER_NAME, EVENT_TYPE, OBJECT_TYPE, OBJECT_NAME
    ) VALUES (
        SYS.LOGIN_USER,
        ORA_SYSEVENT,
        ORA_DICT_OBJ_TYPE,
        ORA_DICT_OBJ_NAME
    );
END STIS_DDL_TRG;
/