--. Basic retrieval 
SELECT 'Total Rows in Tables' AS Table_Name, SUM(cnt) AS Total_Rows FROM (
    SELECT COUNT(*) AS cnt FROM CROP_TYPES
    UNION ALL
    SELECT COUNT(*) AS cnt FROM FARM_SUPPLIES
    UNION ALL
    SELECT COUNT(*) AS cnt FROM PLANTING_BATCHES
) q;

-- Joins 
SELECT 
    b.BATCH_ID,
    c.CROP_NAME,
    s.ITEM_NAME AS SEED_SUPPLY,
    b.PLANTING_DATE,
    b.STATUS
FROM 
    PLANTING_BATCHES b
JOIN 
    CROP_TYPES c ON b.CROP_ID = c.CROP_ID
JOIN 
    FARM_SUPPLIES s ON b.SUPPLY_ID = s.SUPPLY_ID 
WHERE 
    b.STATUS = 'PLANTED'
FETCH FIRST 5 ROWS ONLY;

SELECT 'Verification Complete' FROM DUAL;


-- Aggregation
SELECT ct.CROP_NAME, SUM(pb.AREA_PLANTED_SQM) AS Total_Area_Planted_SQM FROM 
PLANTING_BATCHES pb 
JOIN CROP_TYPES ct ON pb.CROP_ID = ct.CROP_ID 
GROUP BY ct.CROP_NAME ORDER BY 2 DESC;


-- Subquery
SELECT BATCH_ID, CROP_ID, AREA_PLANTED_SQM 
FROM PLANTING_BATCHES 
WHERE AREA_PLANTED_SQM > (SELECT AVG(AREA_PLANTED_SQM) FROM PLANTING_BATCHES) 
FETCH FIRST 5 ROWS ONLY;